# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore PkHex.CLI.csproj
      
    - name: Publish Mac OS ARM64
      run: dotnet publish PkHex.CLI.csproj -r osx-arm64 -c Release
      if: ${{ false }} # disabled as it needs to run on a mac os?
    - name: Publish Linux x64
      run: dotnet publish PkHex.CLI.csproj -r linux-x64 -c Release
    - name: Publish Windows x64
      run: dotnet publish PkHex.CLI.csproj -r win-x64 -c Release
      
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./bin/Release/net8.0/linux-x64/publish/PkHex.CLI
          ./bin/Release/net8.0/win-x64/publish/PkHex.CLI.exe
