# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        config: 
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64
          - os: macos-latest
            rid: osx-arm64

    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish - ${{ matrix.config.rid }}
      run: dotnet publish PkHex.CLI.csproj -r ${{ matrix.config.rid }} -c Release

    - name: Upload - ${{ matrix.config.rid }}
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.config.rid }}
        path: ./bin/Release/net8.0/${{ matrix.config.rid }}/publish

  release:
    runs-on: ubuntu-latest
    needs: publish

    permissions:
      contents: write

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: artifact-*
        run: ls -R

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          artifact-linux-x64/PkHex.CLI
          artifact-win-x64/PkHex.CLI.exe
          artifact-osx-arm64/PkHex.CLI
