# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Get tag version
      id: get_tag
      run: |
        version="${GITHUB_REF##*/}"
        version="${version#v}"
        echo "Version without v: $version"
        echo "::set-output name=version::$version"
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    strategy:
      matrix:
        config: 
          - os: ubuntu-latest
            rid: linux-x64
            artifact:
              from: PKHeX.CLI
              to: pkhex-cli
          - os: windows-latest
            rid: win-x64
            artifact:
              from: PKHeX.CLI.exe
              to: pkhex-cli.exe
          - os: macos-latest
            rid: osx-arm64
            artifact:
              from: PKHeX.CLI
              to: pkhex-cli

    runs-on: ${{ matrix.config.os }}
    needs: test
    if: startsWith(github.ref, 'refs/tags/') # only run publish on tags

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish - ${{ matrix.config.rid }}
      run: dotnet publish ./src/PKHeX.CLI/PKHeX.CLI.csproj -r ${{ matrix.config.rid }} -c Release

    - name: Copy artifact with new name
      run: cp ./src/PKHeX.CLI/bin/Release/net8.0/${{ matrix.config.rid }}/publish/${{ matrix.config.artifact.from }} ./src/PKHeX.CLI/bin/Release/net8.0/${{ matrix.config.rid }}/publish/${{ matrix.config.artifact.to }}

    - name: Upload - ${{ matrix.config.rid }}
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.config.rid }}
        path: ./src/PKHeX.CLI/bin/Release/net8.0/${{ matrix.config.rid }}/publish/${{ matrix.config.artifact.to }}

  release:
    runs-on: ubuntu-latest
    needs: publish
    if: startsWith(github.ref, 'refs/tags/') # only run release on tags

    permissions:
      contents: write

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: List artifacts
      run: ls -R artifacts
    - name: Zip artifacts
      run: |
        zip -j pkhex-cli-linux-x64.zip artifacts/artifact-linux-x64/pkhex-cli
        zip -j pkhex-cli-win-x64.zip artifacts/artifact-win-x64/pkhex-cli.exe
        zip -j pkhex-cli-osx-arm64.zip artifacts/artifact-osx-arm64/pkhex-cli

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        make_latest: true
        generate_release_notes: true
        files: |
          pkhex-cli-linux-x64.zip
          pkhex-cli-win-x64.zip
          pkhex-cli-osx-arm64.zip
